<?php require_once('./includes/head.inc.php') ?>
    <!-- Flickity HTML init -->

    <section class="fit-height">
        <div class="carousel"
             data-flickity='{ "wrapAround": true,"watchCSS": true }'>
            <div class="carousel-cell cellQ">
                <div class="content">
                    <div class="top-content">
                        <img src="./img/ability/Q_spell.png" alt="First ability of BloodHound">
                        <div class="recap-container">
                            <div class="recap">
                                <h2>Eye of the All-father</h2>
                                <h3>[Tactical ability]</h3>
                                <h4>Quick description :</h4>
                                <p>Briefly reveal hidden enemies, traps, and
                                    clues throughout structures ahead of you.</p>
                            </div>
                        </div>
                    </div>
                    <div class="bot-content">
                        <div class="color">
                            <a data-a="cooldown" class="on" href="#cooldown">Cooldown</a>
                            <a data-a="info" class="off" href="#info">Info</a>
                            <a data-a="tips" class="off" href="#tips">Tips</a>
                        </div>
                        <div class="table">
                            <p class="cooldown in">35 Secondes</p>
                            <p class="info out">
                                All nearby enemies and traps are highlighted to be seen
                                by you and your allies. However, even if the highlight is
                                visible for few seconds, it does not follow the movements
                                of players and objects. They so may have moved from what
                                you are actually seeing.
                            </p>
                            <ul class="tips out">
                                <li>Squad mates can also see any scanned enemies or trap.</li>
                                <li>Upon activation, the visual effect generated by
                                    the scan is seen by everyone, including your
                                    teammates and enemies. While you can see the
                                    enemy and their traps, they'll know you're nearby
                                    as well.
                                </li>
                                <li>Eye of the Allfather is not a 360
                                    proximity around Bloodhound. It must be aimed
                                    where you want to reveal enemies. It is roughly
                                    a 90 degree cone in front of you.
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>

            </div>
            <div class="carousel-cell cellP">
                <div class="content">
                    <div class="top-content">
                        <img src="./img/ability/Passive_spell.png" alt="Passive ability of BloodHound">
                        <div class="recap-container">
                            <div class="recap">
                                <h2>Tracker</h2>
                                <h3>[Passive]</h3>
                                <h4>Quick description :</h4>
                                <p>See tracks left behind by your foes.</p>
                            </div>
                        </div>
                    </div>
                    <div class="bot-content">
                        <div class="color">
                            <a data-a="cooldown" class="on" href="#cooldown">Cooldown</a>
                            <a data-a="info" class="off" href="#info">Info</a>
                            <a data-a="tips" class="off" href="#tips">Tips</a>
                        </div>
                        <div class="table">
                            <p class="cooldown in">N/A</p>
                            <div class="info out">
                                <div class="info-container">
                                    <p>
                                        Tracks and certain other actions leave visible traces and highlights for 60
                                        seconds.
                                        Other
                                        actions include:
                                    </p>
                                    <div class="info-flex">
                                        <div>
                                            <p>- Movements Sliding / Jumping / Landings etc...</p>
                                            <p>- Interaction with elements</p>
                                            <p>- Enemy Hurts or killed</p>

                                        </div>
                                        <div>
                                            <p>- Item and weapons pickups</p>
                                            <p>- Emptied magazines</p>
                                            <p>- Pulled Frag Grenades pins</p>

                                        </div>
                                        <div>
                                            <p>- Ability activation</p>
                                            <p>- Bandages used</p>
                                            <p>- Gas and Smoke residue</p>

                                        </div>
                                    </div>
                                </div>
                            </div>

                            <ul class="tips out">
                                <li>When going near tracks, you can call them out to your squad mates using a context
                                    ping
                                    (default h) to share your knowledge with them.
                                </li>
                                <li>Red Tracks are fresh tracks and the enemy is likely nearby.</li>
                                <li>Grey Tracks are old tracks. The enemy hasn't been in that area in about a minute.
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
            <div class="carousel-cell cellR">
                <div class="content">
                    <div class="top-content">
                        <img src="./img/ability/Ultimate_spell.png" alt="Ultimate ability of BloodHound">
                        <div class="recap-container">
                            <div class="recap">
                                <h2>Beast Of The Hunt</h2>
                                <h3>[Ultimate]</h3>
                                <h4>Quick description :</h4>
                                <p>Enhances your senses, allowing you to move faster and highlighting your prey.</p>
                            </div>
                        </div>
                    </div>
                    <div class="bot-content">
                        <div class="color">
                            <a data-a="cooldown" class="on" href="#cooldown">Charge time/Duration</a>
                            <a data-a="info" class="off" href="#info">Info</a>
                            <a data-a="tips" class="off" href="#tips">Tips</a>
                        </div>
                        <div class="table">
                            <p class="cooldown in">180 seconds / 35 seconds</p>
                            <div class="info out">
                                <div class="info-container">
                                    <p>
                                        While active your screen will turn black and white and enemies will be
                                        highlighted
                                        in red.
                                    </p>
                                    <p>
                                        While active you will gain 25% increased movement speed.
                                    </p>
                                    <p>
                                        While active you can also see enemy foot steps.
                                    </p>
                                    <p>
                                        This Ultimate Ability can also see through Bangalore Smoke Launcher and Caustic
                                        Gas.
                                    </p>
                                </div>
                            </div>

                            <ul class="tips out">


                                <li>While active, you can see enemies through Bangalore's or Caustic smokes.
                                </li>
                                <li>Since footsteps are tracked, Beast of the Hunt is a great way of finishing off a
                                    weakened enemy or finding a hiding foe.
                                </li>
                                <li>Since enemies are highlighted in all red, it's much easier to see them from long to
                                    extreme range. This makes Beast of the Hunt a great scouting and sniping skill.
                                </li>
                                <li>
                                    Seeing in black and white only can be troublesome concerning stuff on the ground or
                                    enemies' shields, which you cannot see the color (and so, the level).
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>


<?php require_once('./includes/footer.inc.php'); ?>